branch-defaults:
  local:
    environment: api-test-ripbin
  master:
    environment: api-test-ripbin
global:
  application_name: ripbin.com
  default_ec2_keyname: Ripbin
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.11.2
  default_region: us-west-2
  profile: null
  sc: git
deploy:
  artifact: release-candidate.zip